%% Transfrom a mat into yaml file
% it works if the gaussian has only one prototypes

% Load the MAT file
mat_file = '/var/home/piero/Projects/gdf_recordings/mi_rhlh/calibration/s1/s1_bfbh_20251106.smr.mat';
load(mat_file);

% Create the GaussianCfg structure from the MAT file
GaussianCfg.name = 'gaussian'; 
GaussianCfg.params.filename = strjoin(settings.bci.smr.trace.Paths, '\n    '); 
GaussianCfg.params.subject = settings.info.subject; 
GaussianCfg.params.nclasses = length(settings.bci.smr.taskset.classes);
GaussianCfg.params.classlbs = settings.bci.smr.taskset.classes;
GaussianCfg.params.nprototypes = size(settings.bci.smr.gau.M, 2);
GaussianCfg.params.nfeatures = size(settings.bci.smr.gau.M, 3);
GaussianCfg.params.idchans = settings.bci.smr.channels;

% Convert freqs, covs, and centers into multiline strings if needed
freqs = settings.bci.smr.bands;
freqs = freqs(~cellfun('isempty', freqs));
freqsCellStr = cellfun(@(x) sprintf('%d ', x), freqs, 'UniformOutput', false);
freqsStr = strjoin(freqsCellStr, ';\n');
GaussianCfg.params.freqs = sprintf('%s;', freqsStr); 
covs = reshape(squeeze(settings.bci.smr.gau.C).', [], 1);
covsStr = [strjoin(arrayfun(@(x) sprintf('%.4f', x), covs, 'UniformOutput', false), ';\n'), ';'];
GaussianCfg.params.covs = sprintf('covs: "%s;"\n', covsStr);
centers = reshape(squeeze(settings.bci.smr.gau.M).', [], 1);
centersStr = [strjoin(arrayfun(@(x) sprintf('%.4f', x), centers, 'UniformOutput', false), ';\n'), ';'];
GaussianCfg.params.centers = sprintf('covs: "%s;"\n', centersStr);

% Write to a YAML file  
yamlContent = sprintf(['GaussianCfg:\n' ...
                       '  name: "%s"\n' ...
                       '  params:\n' ...
                       '    subject: "%s"\n' ...
                       '    filename: "%s"\n' ...
                       '    nclasses: %d\n' ...
                       '    classlbs: [%s]\n' ...
                       '    nprototypes: %d\n' ...
                       '    nfeatures: %d\n' ...
                       '    idchans: [%s]\n' ...
                       '    freqs: "%s"\n' ...
                       '    covs: "%s"\n' ...
                       '    centers: "%s"\n'], ...
                       GaussianCfg.name, ...
                       GaussianCfg.params.subject, ...
                       GaussianCfg.params.filename, ...
                       GaussianCfg.params.nclasses, ...
                       strjoin(arrayfun(@(x) sprintf('%.0f', x), GaussianCfg.params.classlbs, 'UniformOutput', false), ', '), ...
                       GaussianCfg.params.nprototypes, ...
                       GaussianCfg.params.nfeatures, ...
                       strjoin(arrayfun(@(x) sprintf('%.0f', x), GaussianCfg.params.idchans, 'UniformOutput', false), ', '), ...
                       freqsStr, ...
                       covsStr, ...
                       centersStr);

splitting = strsplit(mat_file, '/');
file_name = splitting{end};
file_name = [file_name(1:end-3) 'yaml'];
fileID = fopen(file_name, 'w'); % Open the file for writing
fprintf(fileID, yamlContent); % Write the YAML string to the file
fclose(fileID); % Close the file

